apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kushd.fullname" . }}-agent
  labels:
    app.kubernetes.io/component: agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kushd.fullname" . }}-agent
  labels:
    app.kubernetes.io/component: agent
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["pods/eviction"]
    verbs: ["create"]
  - apiGroups: ["policy"]
    resources: ["evictions"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kushd.fullname" . }}-agent
  labels:
    app.kubernetes.io/component: agent
subjects:
  - kind: ServiceAccount
    name: {{ include "kushd.fullname" . }}-agent
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "kushd.fullname" . }}-agent
  apiGroup: rbac.authorization.k8s.io
